### PR TITLE
Updates code to ES2015 style (see body of this request)

### PR DESCRIPTION
**Pull request by jsumners**
This is a big one. It's basically a complete re-write:
- usage of `var` has been completely removed
- big arrow functions are used for `this` scoping, thus removing all references to `self`
- several major methods are refactored into their own modules so that they are easier to follow and maintain (e.g. `find`, `findGroups`, and `findUsers`)
- the underscore.js dependency is completely removed in favor of native methods
- the main `ActiveDirectory` object gained some additional properties and methods
- a lot of jsdoc got added and updated

Along the way a few bugs got fixed. I tried to note them in the commit messages whenever I remembered to do so.

I hope you find all of these changes acceptable.

Note: this is based off my "offline-testing" branch that is already in the pull request queue.

### CODE REVIEW

**Comment by gheeres** [comment]
Do you know what version of node / v8 had full native ES6 support? The package.json fill we need to be updated accordingly.

**Comment by jsumners** [comment]
I would just go with 4.1. I believe everything would be compatible with 0.12, but I'm not going to swear by that. I was using io.js for a long time before the re-merge.

**Comment by jsumners** [comment]
Oh, and please do a check out and test against a real AD server first. I haven't had a chance to do that yet. I have just relied on the tests being accurate.

**Comment by jsumners** [comment]
I doubt you would get to it soon, but hold off on this for now. I've discovered some things that need to be corrected. I will append them to this request and add another message when ready.

**Comment by gheeres** [comment]
Ok. Thanks. Let me know when you're ready.

**Comment by jsumners** [comment]
Okay, I have been able to successfully use every public method (except for `findDeletedObjects` [not configured here]). I am now sufficiently confident that all of these changes work.

I also discovered that I inadvertently wrote the offline testing using ldapjs 1.0.0. So I have updated the dependency in the package.json accordingly. I also update all of the other dependencies.

**Comment by gheeres** [comment]
Thanks for the updates. We actually want to move to ldapjs 1.0.0. I unfortunately haven't had time to look into the changes.

**Comment by jsumners** [comment]
Thank you for figuring out all of the stuff necessary to get ldapjs working with AD. I have a significant project I'm about to start where this library will be a cornerstone.

**Comment by Frank683** [comment]
At the current state of the activedirectory2 project I strongly discourage to merge this pullrequest now because getGroupMembershipForDN runs into an infinite loop and will finally crash the node process.

For details please have a look at this issue: https://github.com/jsumners/node-activedirectory/issues/9

**Comment by jsumners** [comment]
I'm closing this since it has been open over a year, and my fork has diverged even more. I am very open to merging back upstream if @gheeres wants that, though. It'll just take a significant amount of work.

**Pull request closed without merging**
